cd ./build/bin

./mulit_thread_test
./change_IP
./test_namespace
./STL_list_test
./test_UDPserver
./linux_sys_fun_test
./test_UDPclient
./test_tmp
./test_fork
./test_String
./queuetest
./test_linux_timeFun
./condition_test
./variable_length_paraments
./get_threadID_from_processID
./test_TCPserver
./test_TCPclient
./test_ioctl_fun
./test_linux_path_function
./test_regex
./test_printf_multi_char
./test_cpp_io_string
./test_macro
./linuxFooTest
./ifconfig_fun
./test_container
./two_pointers
